# Site settings
title: TinyZ's Blog
description: '专注于网络游戏前后端技术(JAVA, PHP, Unity3D)。积累技术,记录分享。'
url: 'https://github.com/TinyZzh'
baseurl: "/"
rooturl: ""
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'tinyzzh815'

timezone: '+0800' #"Asia/Shanghai"

author:
  name: 'TinyZ'
  email: tinyzzh815@gmail.com
  github_username:  TinyZzh
  linkedin_username:  灼华-周-79326a116

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 5
#permalink: /:year/:title/
#markdown: kramdown  #  [rdiscount, karkdown]
markdown: kramdown  #  [rdiscount, karkdown]
#highlighter: rouge #  [rouge, pygments]

kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'Bootstrap.bat', 'Build.bat']
