# Site settings
title: TinyZ's Blog
description: "专注于网络游戏前后端技术(JAVA, PHP, Unity3D)。积累技术,记录分享。"
permalink: /:categories/:year/:month/:day/:title:output_ext
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://tinyzzh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/MVM-logo-full.svg"
logo-icon: "/assets/img/branding/MVM-symbol.svg"
logo-icon-SEO: "/assets/img/branding/TinyZ-symbol-black.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.                                                                                                                                                 
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/MVM-logo-full-dark.svg"
highlight_theme: syntax-base16.monokai.light # select a dark theme for the code highlighter if needed

# Author settings
author: TinyZ Zzh
author-pic: author_pic.jpg
about-author: 专注于高并发服务器、网络游戏相关(Java、PHP、Unity3D、Unreal Engine等)技术，热爱游戏事业, 正在努力实现自我价值当中。

# Contact links
email: tinyzzh815@gmail.com
phone:
website: https://tinyzzh.github.io # Add your website
linkedin: 灼华-周-79326a116
github: TinyZzh # Add your Github handle
twitter: # Add your Twitter handle
bandcamp: armandomaynez # Add your Bandcamp username
stackoverflow: stackoverflow # Add your stackoverflow account

# Newsletter
mailchimp:

# Disqus
discus_identifier: tinyzzh815
comments_curtain: yes

# Tracker
google_analytics: UA-77019170-1
baidu_analytics: "f5d72321042a4068a214bb314ca29e38"
fbadmin: 

# Paginate
paginate: 6
paginate_path: "page:num"
words_per_minute: 200

extensions:
  mermaid_enable: true
  page_background: branding/page_background_3.jpg
  # [支持暗色模式](https://github.com/mmistakes/minimal-mistakes/discussions/2033#discussioncomment-460914)
  theme_mode:
    dark: [ syntax-base16.monokai.dark, ]
  comments: utteranc  #[disqus, utteranc]
  comments_opts:
    repo: TinyZzh/TinyZzh.github.io
    issue-term: title
    label: comments
    theme: github-dark
    # 仅当使用discus时生效
    discus_identifier: tinyzzh815
    comments_curtain: yes
  date_format: "%Y-%m-%d"

locale: zh
data:
  ui-text:
    zh:
      less_than: 少于
      minute_read: 分钟阅读
      recent_posts: 最 新 文 章

# Build settings
markdown: kramdown

kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: true
mathjax: true
highlighter: rouge

compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: Asia/Shanghai

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude:
  [
    "node_modules",
    "gulpfile.js",
    "package.json",
    "yarn.lock",
    "package-lock.json",
    "assets/css/sass/",
  ]
