# Site settings
title: TinyZ's Blog
description: "专注于网络游戏前后端技术(JAVA, PHP, Unity3D)。积累技术,记录分享。"
url: "https://tinyzzh.github.io"
baseurl: "/"
rooturl: ""
google_analytics: "UA-77019170-1"
baidu_analytics: "f5d72321042a4068a214bb314ca29e38"
disqus_shortname: "tinyzzh815"

# timezone: '+0800' #"Asia/Shanghai"
timezone: "Asia/Shanghai"

author:
  name: "TinyZ"
  email: tinyzzh815@gmail.com
  github_username: TinyZzh
  linkedin_username: 灼华-周-79326a116

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
destination: _site
paginate: 20
#permalink: /:year/:title/
#markdown: kramdown  #  [rdiscount, karkdown]
markdown: kramdown #  [rdiscount, karkdown]
highlighter: rouge #  [rouge, pygments]

kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: nil

plugins: ["jekyll-paginate", "jekyll-archives"]
exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "screenshot.png",
    "1.bundle_install.bat",
    "2.jekyll_bootstrap.bat",
    "3.jekyll_publish.bat",
    "vendor",
  ]
